### ISSUE TITLE
Deathstar renders one word topic titles incorrectly

### ISSUE THREAD

**Issue by mishaone** [jwulf/press-star#23]
One word topic titles render incorrectly in the deathstar. Details in attached conversation:

<misha> ping jwulf 
<jwulf> hey misha
<misha> hey josh
<misha> an odd thing is happening with the deathstar rendering
<misha> http://deathstar1.usersys.redhat.com:3000/builds/14318-Infinispan_Query_Guide/#Overview7
<misha> the title of this topic is just "w"
<misha> the title tags are set correctly and the property is set to Overview as well
<misha> any ideas?
<jwulf> ok
<jwulf> so first off, what has happened here is that hte live patcher has rewritten the title incorrectly
<jwulf> the line underneath the title shows that it's been live patched
<misha> okay
<misha> anything we need to do or should it just fix itself in the next rebuild?
- doug is now known as doug-brb
  <jwulf> it will realign with a rebuild
  <jwulf> but of course i'm interested to know what went wrong to make it more robust
  <misha> cool
  <jwulf> did you change the title in the topic using the editor?
  <misha> nope, jwulf 
  <jwulf> ok
  <jwulf> what i can see here
  <jwulf> is that it's: A one word title
  <jwulf> the last letter is w
  <jwulf> the new title is just "w"
  <misha> yeah
  <jwulf> so it looks like it could be:
  <jwulf> a one word title is incorrectly dealt with
  <jwulf> the last letter might be being dealt with like a space
  <jwulf> so maybe the patcher is preserving a leading space
  <jwulf> and catching the last letter
  <jwulf> i'll look into it
  <misha> thanks jwulf 
  <jwulf> misha: could you do me a big favor, and open a github issue for it?
  <misha> sure jwulf 
  <jwulf> thanks
  <jwulf> maybe just paste in this chat log

**Comment by jwulf** [comment]
The xsl renderer does not insert a space between the section number and the title, but rather Unicode character 160, which is &amp;nbsp;. It looks like a space (which is char code 32), but it's not.

So now we test for charCode 160, rather than ' '.

https://github.com/jwulf/publican-deathstar/commit/4f4874ba570e3936c80e0e5ba3a8f294c073321b

**Comment by jwulf** [comment]
You'll need to rebuild your book to get the new code in it.
