### ISSUE TITLE
xref/ulink/link, something, should be usable across topics in the same book.

### ISSUE THREAD

**Issue by slong9** [jwulf/press-star#37]
Yes, I know, topics are insular by default. And yet, not being able to include inline links to other topics in the same book makes the documentation incredibly clunky. See-also at the end of the topic, especially when it is a long topic just doesn't work that well.  Like putting a car's cup holder back on the trailer. Just not there when you need it. 
So, to avoid punishing the customer because of our tools, could we change the tool?

<link linkend='topicID'>myFavTopic</link>

Perhaps:
---At XML-validation check: would only be invalid if the referenced topic doesn't exist.
---At doc-build check: does the referenced topic exist in the same book? If yes, include; otherwise, either:
--------Find the topic in one of Red Hat's books (preferably the same product), and include the link text, 'myFavTopic', using <citetitle>Red Hat BookName - myFavTopic</citetitle>.
--------Drop the topic reference, but the authoring convention must be that it is used with '(see also <link linkend='topicID'>myFavTopic</link>)', so that the entire authoring clause can be dropped. And, if this is the solution, the XML check could validate that the whole clause, '(refer to xx)', has been used.

This would be a fantastic improvement.

**Comment by slong9** [comment]
Hmm, please look at the code behind this issue.  <citetitle and <link ... are used as possible examples behind myFavTopic.

**Comment by jwulf** [comment]
Skynet injections can do this. I'm not sure where the documentation for skynet injections is. Ask in the #ccms-users channel about them.

There is no support for preview of skynet injections in Press Star at this time. 

At the moment the situation is this:
- you will not get a preview of your injected link.
- you will not be able to validate the topic if it has a skynet injection link that breaks Docbook validity (some versions can do that)
- my understanding is that the build will fail if an injection is specified in a topic and the target is not included in the book (this is a function of the csprocessor component maintained by lnewson)

The one thing that could be added to Press Star as a low-hanging fruit: if a skynet injection is included, and it does not break Docbook validity, then the validator could check that the target is in the book (content spec) and produce a warning if it is not.

If you get to using skynet injections and want that, then please open an issue for it.
