### ISSUE TITLE
Syntax highlighting of </command> is off.

### ISSUE THREAD

**Issue by xsgordon** [jwulf/press-star#40]
When presented with a construct such as &lt;command&gt;rm -rf /_&lt;/command&gt; the syntax highlighter colors the closing element in red (invalid). This doesn't impact on *actual_ validation/saving but is visually distracting. Because the syntax highlighter appears to consider this invalid also tends to mark trailing elements in the same fashion, for instance in this block:

```
<para>
    The volume storage service makes use of the SCSI target daemon, <command>tgtd</command>, when mounting storage. To support this the <command>tgtd</command> service must be configured to read additional configuration files.
</para>
```

Both of the closing &lt;/command&gt; elements and the closing &lt;/para&gt; appear in red in the editor, presumably because the syntax highlight considers the &lt;command&gt; construct to still be open.

**Comment by jwulf** [comment]
It's the command tag that triggers this behaviour.
