### ISSUE TITLE
Possible undeclared dependency (newrelic)?

### ISSUE THREAD

**Issue by xsgordon** [jwulf/press-star#47]
I did a git pull to bring the hoth installation up to date and noticed this:

```
Error: Cannot find module 'bunyan'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:362:17)
    at require (module.js:378:17)
    at Object.<anonymous> (/root/press-star/node_modules/newrelic/lib/logger.js:4:14)
    at Module._compile (module.js:449:26)
    at Object.Module._extensions..js (module.js:467:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:362:17)

module.js:340
    throw err;
```

I performed an install on app.js but it didn't seem to pick up newrelic, finished with:

```
app.js@0.0.16 node_modules/app.js
├── express-rewrite@0.0.3
├── dandy@0.0.5
├── mime@1.2.9
├── underscore@1.4.4
├── cssmin@0.4.1
├── optimist@0.5.2 (wordwrap@0.0.2)
├── vows@0.7.0 (eyes@0.1.8, diff@1.0.4)
├── express-store@0.0.4 (buffers@0.1.1)
├── express-logger@0.0.2 (mkdir@0.0.2, datetime@0.0.3)
├── uglify-js@2.3.6 (optimist@0.3.7, source-map@0.1.22)
├── diskcache@0.0.16 (mkdir@0.0.2, rimraf@2.1.4)
├── express@2.5.9 (qs@0.4.2, mime@1.2.4, mkdirp@0.3.0, connect@1.9.2)
├── transformjs@0.0.3 (uglify-js@1.2.6)
├── jsdom@0.2.2 (cssom@0.2.5, htmlparser@1.7.6, request@2.21.0)
└── hascan@0.0.8 (ua-parser@0.3.3)
```

The error in the app persisted when restarted following this (as you would expect, since it seems newrelic wasn't installed). When I explicitly npm installed newrelic and restarted the app things started working properly.

I'm not overly familiar with the way node deployment works, I can see there is a require on newrelic at the top of app.js but thought I'd best file a bug anyway in case there is some kind of other declaration missing that would result in the behavior I saw.

**Comment by jwulf** [comment]
Well, it's declared here: https://github.com/jwulf/press-star/blob/master/package.json#L28

npm install

is the command that /should/ install it. Or maybe it was npm update...

**Comment by xsgordon** [comment]
I did the npm install but as in the description it didn't seem to pick up the new/added dependency. Probably some caching or something there that doesn't apply if you use update. I am not particularly fussed as I worked it out easily enough and explicitly installed the package, just though I should highlight it.

**Comment by psilva261** [comment]
@xsgordon I just had exactly the same issue when git deploying to a new server. Looks more like an npm issue.
