### ISSUE TITLE
RFE: Auto-link bug ids in revision history.

### ISSUE THREAD

**Issue by xsgordon** [jwulf/press-star#48]
When building the revision history it would be sweet if when encountering BZ#999999 / bz#999999 / bug # 999999 in the commit messages the number was replaced with a ulink to b.r.com/999999. Currently I go through an do this manually.

**Comment by jwulf** [comment]
K, you need to rebuild your book using the updated brand, and then it should pick up anything with BZ#312341 or BZ# 2342134.

So it is triggered by BZ# and you can either have the number with no space, or a single space in-between.

**Comment by jwulf** [comment]
Great idea, btw. Thanks!
