### ISSUE TITLE
Nested topics are not rendered correctly (or at all).

### ISSUE THREAD

**Issue by xsgordon** [jwulf/press-star#52]
The Press Star appears to have some difficulty when it encounters the nested constructs allowed by Bug # 970502 [1]. In content specification 19219 I have this construct:

```
Section: Requirements [19222]
  Hardware Requirements [19230]
  Software Requirements [19231]
```

When I assemble the specification directly using csprocessor all three topics are shown in the output. When I view the version that is available for edit on a Press Star instance and receiving additional JavaScript manipulation however the two nested topics are not displayed.

[1] https://bugzilla.redhat.com/show_bug.cgi?id=970502

**Comment by xsgordon** [comment]
I should note that I an using the "Hoth" Press Star instance and have ensured that Press Star is up to date with master, CSP is up to date (cspclient-0.32.3-2.noarch), and the brand is up to date (publican-deathstar-web-0.50-1.fc18.noarch).

**Comment by xsgordon** [comment]
Interestingly once I hopped over to the CCMS and entered some content in one of the nested topics, then rebuilt on Press Star, both render as you would expect complete with the requisite edit links.

**Comment by jwulf** [comment]
You mean this occurs when the injected topic has no xml content?

**Comment by xsgordon** [comment]
To avoid overloading I'm not talking about injected comments, but rather the fact that the CSP now allows a topic to contain other topics (nesting). If all of the nested topics have no content then they don't appear at all, nor do any edit links etc. Or at least that is the behaviour I observed. Once one of the nested topics has content then they all appear, including their edit links.

**Comment by jwulf** [comment]
Closing. 

So long and thanks for all the fish. 

Long live Corilla!
