### ISSUE TITLE
<para> in nested itemizedlist doesn't render correctly.

### ISSUE THREAD

**Issue by slong9** [jwulf/press-star#53]
In the editor, if there is a new line after the <para> tag in a nested <listitem>, there appears to be a space at the beginning of the contained sentence. The space goes away if you get rid of the NL. That is:

``` <listitem><para>
   text
</para></listitem>
```

appears different from:

``` <listitem><para>text
</para></listitem>
```

There are a few examples here:
http://hoth.usersys.redhat.com:3000/builds/15807-Installation_and_Configuration_Guide/#Installation_Prerequisites_Checklists

``` <entry>
                            <para>
                                You must have a subscription to: 
                                <itemizedlist>
                                    <listitem>
                                        <para>
                                            Receive package updates from Red Hat Network or an equivalent source such as a Red Hat Network Satellite server.
                                        </para>
                                    </listitem>
                                    <listitem>
                                        <para>
                                            Receive software updates for both Red Hat Enterprise Linux 6.4 Server and Red Hat OpenStack
                                        </para>
                                    </listitem>
                                </itemizedlist>
                            </para>
                    </entry>
```

**Comment by slong9** [comment]
Please look at the html of that issue, the tags aren't being rendered...

**Comment by jwulf** [comment]
To get html tags to render verbatim here you need to use entities (like &amp;amp;) or else escape them with three back ticks: ` ` ` (with no spaces between them). To close the escaping, put another three backticks on a blank line.

**Comment by jwulf** [comment]
Does it behave like this (the phantom whitespace) on the docs stage?

**Comment by slong9** [comment]
No, it brews fine. Looks like it's just an editor problem. And I started to fix all of them (by getting rid of the new line), then realised that it wasn't real. :)
